name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Create release
        uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          